services:
  - type: web
    name: poultry-farm-ml
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn cloud_ml_server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FIREBASE_URL
        value: https://poultry-ai-e901a-default-rtdb.firebaseio.com
    healthCheckPath: /health
